### PR TITLE
Adding repo.json for plugin installation

### LINKED ISSUE #1: repo.json
Add repos.json file for installation via `micro -plugin install`.
The [documentation](https://github.com/zyedidia/micro/blob/75b9a6cefed4fc325888ad93e356ec4f2ea1341d/runtime/help/plugins.md#plugin-manager) talks about this in more detail.

### PR DESCRIPTION
**Pull request by ghost**
Closes #1

### CODE REVIEW

**Comment by gaenseklein** [comment]
gittab is in very early WIP. it does not have any benefit at all for users as it is right now. 

furthermore i dont know if repo.json is still needed, as the maintainer of micro does not want to continue this way of distribution. 

so i dont see any reason to include repo.json right now and help to install it. i am not even shure if i will continue this plugin as i see some roadblocks ahead which seems to cost a lot of work for very small benefit. but that has to decide the future me, the current me is working on other things for now. 

if you want to see gittab working you could fork and continue the work. i dont know if and when i will continue it.

**Comment by ghost** [comment]
> [...] i dont know if repo.json is still needed, as the maintainer of micro does not want to continue this way of distribution.

Will repo.json be abandoned ? What will be the other way of distributing plugins? If you have the link to this speech it would be of great help.
I have a [fork](https://github.com/taconi/plugin-channel) with plugin-channel so that interests me a lot.

> [...] i see some roadblocks ahead which seems to cost a lot of work for very small benefit. [...]

I believe you can open issues about the problems that are occurring or even about the ones you are developing or what would be cool to be developed, so I or someone else can help with these issues.
Maybe I'm dreaming a little big but this plugin could be like emacs [magit](https://magit.vc/)

**Comment by gaenseklein** [comment]
> Will repo.json be abandoned ? What will be the other way of distributing plugins? If you have the link to this speech it would be of great help.

if i understand [this announcement](https://github.com/zyedidia/micro/discussions/2669) correctly yes, its kind of abandoned. i mean it will still work "the old way" by users manualy altering their settings.json to include the 3rd-party-repo, but its not meant to be the way plugins are distributed "by default". the author of micro seems to want to go to a mono-responsibility / mono-source-of-trust where the plugins will be hosted and reviewed by the author him or herself. 
to me this sounds like hosting your own repo with repo.json does not make sense any more aside you want to have control over the plugins versions. as i dont plan to support more then one version of each plugin (the current one) this does not make sense to me. git does a way better job there and is way more comfortable. just git pull and you have the most actual version.  
if i would want to use repo.json i would want to host a "real" repo - a gaenseklein-repo which includes all of my plugins so you dont have to enter a repo for every plugin. a repo.json per plugin is just a waste of time and effort in my opinion right now. before that change to mono-responsibility your repo for your plugin would enter the default settings.json if approved by micros author, therefore it made sense to host your own repo.json. 

> I have a [fork](https://github.com/taconi/plugin-channel) with plugin-channel so that interests me a lot.

thats a different approach and reflects the announcement mentioned above. the repo.json is not used anywhere in there - although its kind of confusing because you use another repo.json like style to host your plugin. so i think repo.json is "the old way" and nearly abandoned. that is at least what i took from all of this and therefore questioned myself why bother with repo.json. for users of my plugins i recommend using git to get the most-up-to-date version, for default-plugin i will do the micro-plugins-channel way and hope the maintainer of it will include my plugin and updates of it. 


> I believe you can open issues about the problems that are occurring or even about the ones you are developing or what would be cool to be developed, so I or someone else can help with these issues.
> Maybe I'm dreaming a little big but this plugin could be like emacs [magit](https://magit.vc/)


well, i never thought that gittab will be something like that. the way gittab is meant to work is like the git tab in atom: you have an overview over your current unstaged changes, followed by staged changes, a textfield for a commit-message and a button to commit, followed by an overview over the last commits with the ability to undo them:
atoms-gittab


when you are on an unstaged or stanged change you can stage/unstage it with hitting "enter", you can open up a diff of it with "tab" and then inside you can stage/unstage changes by blocks or lines. 

you can then commit with the commit-message. 

atom has externalized git-fetch, git-pull, and git-push - which i would obviously integrate into gittab. maybe also creating/switching branches. 

that said, its not a real blocker but i think that it takes some effort to write it. as i was used to this workflow i wanted to integrate it into micro - but after using commandline git for some time now and in spite of the fact that there are a lot of advanced git-guis out there (even for commandline) i dont see it that more valuable to me. instead with atom i had the bad behaviour to not commit for a long time and then instead of making one big commit i would use atom with the workflow described above to create a chain of commits to group the changes together in "sensefull commits". i want to be frank - this is a waste of time. with the command-line i do a commit as soon as the change is done and this seems to me favourable as i dont waste time to read the diff, separating them into groups, then commit them one by one. 

maybe i will write it to help some compas getting finaly rid of atom and not switching to vs-code. but for now i have other prioritys. 

so if you want to have something like magit you should write your own, i never intented to do something like this with gittab. feel free to use the code of gittab as it could help you to start. but maybe a fresh start would be better.

**Comment by ghost** [comment]
Ok, thanks for clarifying

**Comment by ghost** [comment]
By the way, if you are used to git in the terminal maybe [lazygit](https://github.com/jesseduffield/lazygit) will be interesting

**Pull request closed without merging**
